name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Bundler and dependencies
        run: |
          gem install bundler -v 2.4.22 --no-document --user-install
          bundle config path vendor/bundle
          bundle install

      - name: Build website
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "dsbioanalytics@gmail.com"
          git config --global user.name "Xenophong"
          git add .
          git commit -m "Update website"
          git push origin main
