
name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true 

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Build website
        run: |
          # Fetch latest changes from the main branch
          git fetch origin main

          # Reset the local main branch to match the fetched changes
          git reset --hard origin/main

